### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by do-my-best** [panghaijiao/HJTabViewController#1]
下载后无法解压,而且 pod 上也搜不到HJTabViewController,git clone 也无法下载

**Comment by panghaijiao** [comment]
目前暂时没有上传到master repo上面，可以直接使用  pod 'HJTabViewController',     :git => 'https://github.com/panghaijiao/HJTabViewController.git'

**Comment by panghaijiao** [comment]
我这边下载是可以解压的

**Comment by do-my-best** [comment]
pod install 的时候提示 Unable to find a specification for `HJTabViewController`

**Comment by do-my-best** [comment]
我又重新下载了一次,可以了,谢谢了哈
