### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by yilongchun** [panghaijiao/HJTabViewController#2]
我新建了一个工程，将HJTabViewBar和JHTabViewController两个文件夹和HeaderTabViewController,TableViewController两个文件拖到新工程，直接显示HeaderTabViewController，报错，提示
Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [187.5 nan]'
能帮忙看看是什么错误吗

**Comment by panghaijiao** [comment]
是crash吗？崩到哪一行了

**Comment by yilongchun** [comment]
是闪退，下面是错误
Terminating app due to uncaught exception 'CALayerInvalidGeometry', reason: 'CALayer position contains NaN: [187.5 nan]'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001106d7b0b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010fe90141 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000110740625 +[NSException raise:format:] + 197
	3   QuartzCore                          0x000000011604b0be _ZN2CA5Layer12set_positionERKNS_4Vec2IdEEb + 152
	4   QuartzCore                          0x000000011604b231 -[CALayer setPosition:] + 43
	5   QuartzCore                          0x000000011604b851 -[CALayer setFrame:] + 610
	6   UIKit                               0x0000000111287fe9 -[UIView(Geometry) setFrame:] + 845
	7   UIKit                               0x00000001113f3e0c -[UIImageView _setViewGeometry:forMetric:] + 176
	8   UIKit                               0x00000001113f403c -[UIImageView setFrame:] + 58
	9   testtable                           0x000000010f8a7bef -[TableViewController viewDidLoad] + 1119
	10  UIKit                               0x000000011138701a -[UIViewController loadViewIfRequired] + 1235
	11  UIKit                               0x000000011138745a -[UIViewController view] + 27
	12  testtable                           0x000000010f8a4f85 -[UIViewController(tabViewController) tabContentScrollView] + 149
	13  testtable                           0x000000010f8a73d1 -[HJTabViewControllerPlugin_HeaderScroll addPanGestureForIndex:] + 113
	14  testtable                           0x000000010f8a71f9 -[HJTabViewControllerPlugin_HeaderScroll loadPlugin] + 89
	15  testtable                           0x000000010f8ae76f __34-[HJTabViewController loadPlugins]_block_invoke + 95
	16  CoreFoundation                      0x0000000110668652 __53-[__NSArrayM enumerateObjectsWithOptions:usingBlock:]_block_invoke + 114
	17  CoreFoundation                      0x000000011066850f -[__NSArrayM enumerateObjectsWithOptions:usingBlock:] + 239
	18  testtable                           0x000000010f8ae6e3 -[HJTabViewController loadPlugins] + 99
	19  testtable                           0x000000010f8aafb5 -[HJTabViewController loadContentView] + 133
	20  testtable                           0x000000010f8a9769 -[HJTabViewController viewDidLayoutSubviews] + 73
	21  UIKit                               0x00000001112a75db -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1396
	22  QuartzCore                          0x0000000116054904 -[CALayer layoutSublayers] + 146
	23  QuartzCore                          0x0000000116048526 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 370
	24  QuartzCore                          0x00000001160483a0 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	25  QuartzCore                          0x0000000115fd7e92 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 294
	26  QuartzCore                          0x0000000116004130 _ZN2CA11Transaction6commitEv + 468
	27  QuartzCore                          0x0000000116004b37 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 115
	28  CoreFoundation                      0x000000011067d717 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	29  CoreFoundation                      0x000000011067d687 __CFRunLoopDoObservers + 391
	30  CoreFoundation                      0x0000000110662038 CFRunLoopRunSpecific + 440
	31  UIKit                               0x00000001111de08f -[UIApplication _run] + 468
	32  UIKit                               0x00000001111e4134 UIApplicationMain + 159
	33  testtable                           0x000000010f8b289f main + 111
	34  libdyld.dylib                       0x0000000113a0c65d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by panghaijiao** [comment]
看堆栈好像是在设置UIImageView的frame时算出了负数，可以试试把UIImageView去掉试试

**Comment by yilongchun** [comment]
我知道问题了 是没有把 2 3图片拷过来 ，谢了

**Comment by panghaijiao** [comment]
好的
