### ISSUE TITLE
底部有tabbar时，不能滑动问题

### ISSUE THREAD

**Issue by zfx5130** [panghaijiao/HJTabViewController#28]
如果是tabbar控制的自控制器，就会出现上下滑动悬停滑动

**Comment by panghaijiao** [comment]
不是很明白，这个与底部tabbar应该没关系吧

**Comment by zfx5130** [comment]
有，我试过了， 如果跳转 隐藏 用self.hidesBottomBarWhenPushed = YES;  隐藏tabbar就没问题， 具体能加你么，帮忙看下，

**Comment by zfx5130** [comment]
已解决，感谢作者提供帮助
