### ISSUE TITLE
你好，如果子页面里面含有2个tableView的话，怎么设置hj_tabContentScrollView返回值

### ISSUE THREAD

**Issue by zfx5130** [panghaijiao/HJTabViewController#34]
在一个VC中，添加左右2个tableView，设置hj_tabContentScrollView，但是只有一个能上下联动，怎么处理下面的返回值，同步2个呢，谢谢

- (UIScrollView *)hj_tabContentScrollView {
    return self.leftTableView ;
}

**Comment by panghaijiao** [comment]
两个tableview同时滑动？

**Comment by zfx5130** [comment]
@panghaijiao  一个VC里面添加2个Tableview ，下面的这个方法只能设置一个tableView,一个这个tableview滑动会联动整体菜单栏滑动，但是另外一个tableview不会联动菜单栏滑动，这个怎么处理，
（UIScrollView *）hj_tabContentScrollView {
return self.leftTableView;
}

**Comment by zfx5130** [comment]
@panghaijiao  请问有办法解决吗，
