### ISSUE TITLE
HeaderTabViewController中的问题

### ISSUE THREAD

**Issue by gx2015** [panghaijiao/HJTabViewController#5]
经测试 当有至少3个子VC的时候，第一次进入该VC滚动scrollview到顶部，然后快速切换子VC会发现后面的子VC留有空白。这是如果再切换的话，就会出现跳动问题。如果滚动的慢的话就不会出现此类问题。该问题出现在快速滑动的时候。
![7ecbe02bc429bd19cc344e63ba9902ad](https://user-images.githubusercontent.com/10735111/30424218-da4cd2f2-9977-11e7-8c1b-c05b9543bcab.png)

**Comment by gx2015** [comment]
楼主 可以测试看看

**Comment by panghaijiao** [comment]
上下滚动是因为scrollView的consize高度太小，不足以支撑滚动到底部

**Comment by gx2015** [comment]
不是 我下载的源码 然后自己测试发现的 什么也没改动

**Comment by gx2015** [comment]
我是运行的源码：进入HeaderTabViewController中滚动HeaderView到顶部悬浮，然后<快速>向右滑动切换（测试的子VC有3个以上）会发现某个子VC的顶部留白就是我发的那种图片 楼主可以测测。

**Comment by panghaijiao** [comment]
我把数量改成5貌似没有重现

**Comment by panghaijiao** [comment]
哦，我明白你的意思了

**Comment by panghaijiao** [comment]
后面我看看，正常情况你在ViewDidAppear在加载界面就没问题，不要在didLoad里面加载UI

**Comment by gx2015** [comment]
对 比如说有5个 滑动快点儿 一个接一个 不要等一个停止后再滑动 就是一个还没停止 就滑到下一个 容易出现这个问题 而且是刚进来这个VC的时候 先让TabHeader滚动到顶部再滑动。

**Comment by gx2015** [comment]
也不一定非得滑到顶部，就是一开始进入这个页面后，先向上滑动一段距离，然后快速横向滑动，就易出现顶部留白的问题

**Comment by panghaijiao** [comment]
这个是因为我demo界面实在viewdidload里面加载UI的，你在viewdidappear加载UI就OK了，最好不要再didload里面加载，界面多了，进界面所有子页面会全部加载，这样非常耗性能

**Comment by gx2015** [comment]
具体是哪个类 HJTabViewController？ 如果是这个类 viewDidLoad里面就只是加载了容器视图

**Comment by panghaijiao** [comment]
你自己的子VC

**Comment by panghaijiao** [comment]
HJTabViewController容器什么都不用处理

**Comment by gx2015** [comment]
在你的demo里 具体是哪个类？ 我测试一下

**Comment by panghaijiao** [comment]
所有HJTabViewController的子类都是父容器，里面的TableViewController都是业务子VC

**Comment by gx2015** [comment]
就是说 HJTableViewController里面什么也不用改？我刚才修改了TableViewController里面的代码 就是一个简单的Table 就算把UI挪到didAppear 也还是会出现那个问题 而且还会出现加载延迟

**Comment by gx2015** [comment]
能更新一下代码吗？ 多谢！

**Comment by gx2015** [comment]
不好意思 感觉好像咱俩说的不是一个VC 我说的是那个带HeaderView的情况，如下截图：
![1](https://user-images.githubusercontent.com/10735111/30465476-f4755162-9a09-11e7-8164-2db5d2a5f727.png)
楼主 可以再测试看看 先向上移动 再快速滑动 就会出现图中问题

**Comment by panghaijiao** [comment]
你说的这个问题我知道的，是因为右边这个界面没出现之前UI就加载出来了，所以导致左边界面滑上去后，右边没有滑动上去，你可以等右边这个界面的didappeare出现后再加载UI就没这个问题了，后面我会针对didload加载的UI问题优化

**Comment by gx2015** [comment]
那什么时间可以看到新版本？

**Comment by panghaijiao** [comment]
目前版本就可以满足需求，你只要在各个子界面的viewdidappear里面加载数据UI就没这个问题了

**Comment by panghaijiao** [comment]
如果你不想要那个自动回滚到下面，可以开启 HJTabViewControllerPlugin_BottomInset插件

**Comment by gx2015** [comment]
[1.mp4.zip](https://github.com/panghaijiao/HJTabViewController/files/1305394/1.mp4.zip)

我录了一个3s的小视频 你看看这个情况 ？如果不从数据上去处理的话，还有没有其他方式？

**Comment by panghaijiao** [comment]
等我fix好通知你，你先在viewdidappear加载数据UI解决，正常情况也不应该在viewdidload里面加载数据

**Comment by panghaijiao** [comment]
1.0.2已解决此问题，过段时间就可以更新了，感谢提的问题，到时验证下

**Comment by panghaijiao** [comment]
目前1.0.2已经可以在pod中搜索到，验证没问题记得close issue

**Comment by gx2015** [comment]
已验证：OK
