### ISSUE TITLE
下拉刷新

### ISSUE THREAD

**Issue by gx2015** [panghaijiao/HJTabViewController#6]
可否在外层（顶部，不是子控制器内）添加下拉刷新控件？

**Comment by panghaijiao** [comment]
你可以在每个子界面顶部加一个下拉刷新，这个刷新UI向上便宜到顶部，然后把headerview背景色设置为透明就可以了

**Comment by gx2015** [comment]
试过了 但是如果header固定在顶部 并且里面还有图片的话 刷新控件会被覆盖 看不见?

**Comment by gx2015** [comment]
按照层级关系的话 header肯定在scrollview的上层 必然会盖住scrollview内部子VC视图的刷新控件

**Comment by panghaijiao** [comment]
你可以下载ERYU首页看看效果，headerview做一个容器，背景设置透明，图片add到header里面，向下对齐，高度固定，这样下滑图片下移不就可以看到后面的刷新控件了

**Comment by gx2015** [comment]
对 这种效果还行，如果是图片放在顶部要下拉放大就不行了 主要还是看产品需求

**Comment by panghaijiao** [comment]
图片下拉还需要下拉，这个就有点冲突了

**Comment by dxpbloom** [comment]
你好，大佬，我想问下HeaderTabViewController 子tableview里面加MJRefresh 的 MJRefreshNormalHeader 下拉刷新，这个怎么实现，下拉后，顶部会跟着往下走，没有下拉刷新的效果，这个能实现吗？
