### ISSUE TITLE
HeaderTabViewController不好使了

### ISSUE THREAD

**Issue by pengpeng-wang** [panghaijiao/HJTabViewController#7]
HeaderTabViewController内容下移了64

**Comment by panghaijiao** [comment]
什么意思

**Comment by pengpeng-wang** [comment]
iOS11上你的demo里，第三项HeaderTabViewController这个 点不进去了，我的项目里图片下面的UI下移了64，找了半天没找到问题，只有iOS11有问题

**Comment by panghaijiao** [comment]
有截图吗？iOS11系统改动很大

**Comment by pengpeng-wang** [comment]
加我QQ吧：841987035，GitHub传文件一直传不上去

**Comment by panghaijiao** [comment]
等我先适配iOS11完你再试试

**Comment by pengpeng-wang** [comment]
ok

**Comment by panghaijiao** [comment]
最新1.0.4版本已适配iOS11，已经上传pod，等待审核过后验证下

**Comment by pengpeng-wang** [comment]
我看到加了这个，可以了，谢谢！
if (@available(iOS 11.0, *)) {
    scrollView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
}

**Comment by liaohengjie** [comment]
可以把刷新也加上吗？

**Comment by panghaijiao** [comment]
你说的是下拉刷新？可以的，参考 https://github.com/panghaijiao/HJTabViewController/issues/6
